# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'dyn_meta'
require 'i18n'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before :suite do

    require "i18n/backend/fallbacks"
    I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
    I18n.fallbacks.map(:"en-US" => :en)

    I18n.backend.store_translations(:en, {
      'meta' => {
        'page_titles' => {
          'default' => 'Default page title',
          'testing' => {
            'default' => 'Default testing controller page title',
            'show' => 'Testing controller show action page title'
          }
        },
        'keywords' => {
          'default' => 'dyn_meta',
          'testing' => {
            'default' => 'testing,dyn_meta',
            'show' => 'testing,show,dyn_meta',
            'index' => 'testing,index,dyn_meta,%{type}'
          },
          'pages' => {
            'default' => 'pages,default,dyn_meta',
            'show' => {
              'default' => 'pages,show,default,dyn_meta',
              'tos' => 'pages,show,tos,dyn_meta'
            }
          }
        }
      }
    })

    I18n.backend.store_translations(:"en-US", {
      'meta' => {
        'page_titles' => {
          'default' => 'Default page title in the US'
        }
      }
    })

  end
end
